app/finance/models.py
import datetime
import uuid

from sqlalchemy.orm import backref

from ..auth.models import User
# from ..organization.models import Employee
from flask_login import current_user

from .. import db


class Operation:
    CREDIT = 'CR'
    DEBIT = 'DB'
    OPERATION = (
        (CREDIT, 'Credit'),
        (DEBIT, 'Debit'),
    )

class TimeUnit:
    DAY = 'D'
    MONTH = 'M'
    YEAR = 'Y'
    UNIQUE = 'U'
    TIME_UNIT = (
        (UNIQUE, 'unique'),
        (DAY, 'day'),
        (MONTH, 'month'),
        (YEAR, 'year'),
      )


class FinancialTransaction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(64))
    value = db.Column(db.Numeric)
    date = db.Column(db.DateTime(), default=datetime.datetime.utcnow)
    transaction_id = db.Column(db.String(16), default=str(uuid.uuid4()))
    employee_id = db.Column(db.Integer, db.ForeignKey('employee.id'))
    product_purchase_oders = db.relationship('ProductPurchaseOrder', backref=backref('financial_transaction', cascade='all'))
    product_sales_oders = db.relationship('ProductSalesOrder', backref=backref('financial_transaction', cascade='all'))

    @property
    def total_group_value(self):
        total_value = 0
        items = self.query.filter_by(transaction_id=self.transaction_id)
        for item in items:
            total_value += item.value
        return total_value

    def __repr__(self):
        return self.description

app/finance/forms.py
from wtforms import StringField, SelectField, DecimalField, IntegerField, DateTimeField
from wtforms.validators import Required, Length, NumberRange, Optional
from flask_wtf import Form

from ..organization.models import Customer, Supplier

from .models import FinancialTransaction


class FinancialTransactionForm(Form):
    description = StringField(validators=[Required(), Length(1, 64)])
    value = DecimalField(validators=[Required()])
    date = DateTimeField(validators=[Required()])
    transaction_id = StringField(validators=[Required(), Length(16)])
    employee_id = StringField(validators=[Required()])

app/finance/__init__.py
# from flask import Blueprint

# finance = Blueprint('finance', __name__, template_folder='templates')

# from . import views

app/finance/views.py
import datetime
from dateutil.relativedelta import relativedelta

from sqlalchemy.sql import func

from flask import Blueprint, render_template, redirect, request, url_for, flash, current_app
from flask_login import current_user, login_required

from .. import db

from ..views import ListView, CreateView, UpdateView, DeleteView

from .models import FinancialTransaction
from .forms import FinancialTransactionForm

finance = Blueprint('finance', __name__, template_folder='templates', url_prefix='/finance')


#finance
finance.add_url_rule('/', view_func=ListView.as_view('list_financial_transaction', FinancialTransaction))
finance.add_url_rule('/add/', view_func=CreateView.as_view('create_financial_transaction', FinancialTransaction, FinancialTransactionForm))
finance.add_url_rule('/<int:id>/', view_func=UpdateView.as_view('edit_financial_transaction', FinancialTransaction, FinancialTransactionForm))
finance.add_url_rule('/<int:id>/delete', view_func=DeleteView.as_view('delete_financial_transaction', FinancialTransaction))

today = datetime.date.today()

@finance.route('/report/daily/', defaults={'year':today.year, 'month':today.month, 'day':today.day})
@finance.route('/report/<int:year>/<int:month>/<int:day>/')
@login_required
def report_by_day(year, month, day):
    view_name = 'report_by_day'
    model = FinancialTransaction
    today = datetime.date.today()
        
    date = datetime.date(year=year, month=month, day=day)
    previous_date = date - relativedelta(days=1)
    next_date = date + relativedelta(days=1)
    
    items = model.query.filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month, func.extract('day', model.date)==day).all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month, func.extract('day', model.date)==day)
    total_value = items_func.first().total_value

    return render_template('report_by_day.html', 
        items=items,
        view_name=view_name,
        year=year,
        month=month,
        day=day,
        today=today,
        previous_date=previous_date,
        next_date=next_date,
        total_value=total_value)


# @finance.route('/report/')
@finance.route('/report/monthly/', defaults={'year':today.year, 'month':today.month})
@finance.route('/report/<int:year>/<int:month>/', methods=['GET', 'POST'])
@login_required
def report_by_month(year, month):
    view_name = 'report_by_month'
    model = FinancialTransaction
    today = datetime.date.today()
    
    year = today.year if not year else year
    month = today.month if not month else month   
    day = today.day if month == today.month else 1
    
    date = datetime.date(year=year, month=month, day=day)
    previous_date = date - relativedelta(months=1)
    next_date = date + relativedelta(months=1)
    
    items = model.query.filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month).all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month)
    total_value = items_func.first().total_value
    
    return render_template('report_by_month.html', 
        items=items,
        view_name=view_name,
        year=year,
        month=month,
        day=day,
        today=today,
        previous_date=previous_date,
        next_date=next_date,
        total_value=total_value)


@finance.route('/report/yearly/', defaults={'year':today.year})
@finance.route('/report/<int:year>/')
@login_required
def report_by_year(year):
    view_name = 'report_by_year'
    model = FinancialTransaction
    today = datetime.date.today()
        
    month = today.month if year == today.year else 1
    day = today.day if month == today.month else 1

    date = datetime.date(year=year, month=month, day=day)
    previous_date = date - relativedelta(years=1)
    next_date = date + relativedelta(years=1)
    
    items = model.query.filter(func.extract('year', model.date)==year).all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(func.extract('year', model.date)==year)
    total_value = items_func.first().total_value
    
    return render_template('report_by_year.html', 
        items=items,
        view_name=view_name,
        year=year,
        month=month,
        day=day,
        today=today,
        previous_date=previous_date,
        next_date=next_date,
        total_value=total_value)

@finance.route('/report/transaction/', defaults={'transaction_id':None})
@finance.route('/report/transaction/<transaction_id>/')
@login_required
def report_by_transaction(transaction_id):
    view_name = 'report_by_transaction'
    model = FinancialTransaction
    
    if transaction_id:
        items = model.query.filter_by(transaction_id=transaction_id).all()
    else:
        items = model.query.all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(model.transaction_id==transaction_id)
    total_value = items_func.first().total_value
 
    return render_template('report_by_transaction.html', 
        items=items,
        view_name=view_name,
        transaction_id=transaction_id,
        total_value=total_value)



# @finance.route('/add/', methods=['GET', 'POST'])
# def create_financial_transaction():
# 	print dir(current_user)
# 	view_name = 'financial_transaction'
# 	form = FinancialTransactionForm()
# 	if form.validate_on_submit():
# 	    item = FinancialTransaction(
# 	        description=form.description.data,
# 	        value=form.value.data,
# 	        employee_id=current_user.id)
# 	    db.session.add(item)
# 	    db.session.commit()
# 	    flash('Item has been recorded.')
# 	    return redirect(url_for('.edit_'+view_name, id=item.id))
# 	return render_template('form.html', form=form, view_name=view_name)

app/product/views.py
import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app, jsonify
from flask_login import login_required, current_user

from ..views import ListView, CreateView, UpdateView, DeleteView
from .. import db
# from . import product

from .models import Status, Product, ProductPurchaseOrder, ProductPurchaseItem, ProductSalesOrder, ProductSalesItem
from .forms import ProductForm, ProductPurchaseOrderForm, ProductPurchaseOrderUpdateForm, ProductPurchaseItemForm, ProductSalesOrderForm, ProductSalesItemForm
from ..organization.models import Supplier
from ..finance.models import FinancialTransaction

product = Blueprint('product', __name__, template_folder='templates', url_prefix='/product')


#product
product.add_url_rule('/product/', view_func=ListView.as_view('list_product', Product))
product.add_url_rule('/product/add/', view_func=CreateView.as_view('create_product', Product, ProductForm))
product.add_url_rule('/product/<int:id>/', view_func=UpdateView.as_view('edit_product', Product, ProductForm))
product.add_url_rule('/product/<int:id>/delete', view_func=DeleteView.as_view('delete_product', Product))
# product.add_url_rule('/purchase/', view_func=ListView.as_view('list_product_purchase_order', ProductPurchaseOrder))


#product_purchase_order
@product.route('/purchase/')
@login_required
def list_product_purchase_order():
    view_name = 'product_purchase_order'
    model = ProductPurchaseOrder
    page = request.args.get('page', 1, type=int)
    pagination = model.query.paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'], error_out=False)
    items = pagination.items
    return render_template('purchase_order/list.html', 
        items=items,
        pagination=pagination, 
        view_name=view_name,
        parent_view_name='product_purchase_item')


@product.route('/purchase/add/', methods=['GET', 'POST'])
@login_required
def create_product_purchase_order():
    view_name = 'product_purchase_order'
    form = ProductPurchaseOrderForm()
    if form.validate_on_submit():
        item = ProductPurchaseOrder(
            employee_id=current_user.id,
            supplier_id=form.supplier.data,
            status=Status.CREATED
        )
        db.session.add(item)
        db.session.commit()
        flash('Item has been recorded.')
        return redirect(url_for('.create_product_purchase_item', parent_id=item.id))
    return render_template('form.html', form=form, view_name=view_name)


@product.route('/purchase/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete_product_purchase_order(id):
    view_name = 'product_purchase_order'
    model = ProductPurchaseOrder
    item = model.query.get_or_404(id)
    db.session.delete(item)
    flash('Item has been deleted.')
    return redirect(url_for('.list_'+view_name))

# @product.route('/purchase/add/', methods=['GET', 'POST'])
@product.route('/purchase/<int:parent_id>/', methods=['GET', 'POST'])
@product.route('/purchase/<int:parent_id>/<status>/', methods=['GET'])
@login_required
def create_product_purchase_item(parent_id=None, status=None):
    view_name = 'product_purchase_item'

    parent = ProductPurchaseOrder.query.get(parent_id)
    parentForm = ProductPurchaseOrderForm()
    print (parent)

    """
    Se <status> for igual a:
    1. CREATED = somente neste status o pedido pode ser alterado.
    2. PLACED = envia email ao fornecedor solicitando a cotacao.
    3. PAID = registra uma transacao financeira.
    4. AVAILABLE = adiciona a quantidade comprada do item ao produto e lanca o valor da compra como despesa.
    """
    if status:
        print (status)
        parent.status = status
        if status == Status.AVAILABLE:
            for product in parent.items:
                product.product.quantity += product.quantity

            parent.financial_transaction = FinancialTransaction(
                description = 'Purchase Order: %s' % parent,
                value = parent.total_value,
                employee_id=current_user.id)
        # if status == Status.PAID:

            
        # db.session.add(parent)
        return redirect(url_for('.create_'+view_name, parent_id=parent_id))

    form = ProductPurchaseItemForm()
    if form.validate_on_submit():
        item = ProductPurchaseItem(
            order_id=parent_id,
            product_id=form.product.data,
            quantity=form.quantity.data,
            value=form.value.data,
            status=Status.CREATED)
        db.session.add(item)
        db.session.commit()
        flash('Item has been recorded.')
        return redirect(url_for('.edit_'+view_name, 
            parent_id=item.order.id, 
            id=item.id))

    page = request.args.get('page', 1, type=int)
    pagination = ProductPurchaseItem.query.filter_by(order_id=parent_id).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    items = pagination.items
    return render_template('purchase_item/form_list.html',
        view_name=view_name,
        form=form,
        parentForm=parentForm,
        items=items,
        pagination=pagination, 
        parent=parent)


@product.route('/purchase/<int:parent_id>/item/<int:id>/', methods=['GET', 'POST'])
@login_required
def edit_product_purchase_item(parent_id, id):
    view_name = 'product_purchase_item'
    form = ProductPurchaseItemForm()
    item = ProductPurchaseItem.query.get_or_404(id)
    if form.validate_on_submit():
        item.product_id = form.product.data
        item.quantity = form.quantity.data
        item.value = form.value.data
        db.session.add(item)
        flash('Item has been updated.')
        return redirect(url_for('.edit_'+view_name, 
            id=item.id,
            parent_id=item.order.id))
    form.product.data = item.product_id
    form.quantity.data = item.quantity
    form.value.data = item.value

    page = request.args.get('page', 1, type=int)
    pagination = ProductPurchaseItem.query.filter_by(order_id=parent_id).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    items = pagination.items
    return render_template('purchase_item/form_list.html', 
        view_name=view_name,
        form=form,
        items=items,
        pagination=pagination, 
        id=id,
        parent=item.order)


@product.route('/purchase/item/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete_product_purchase_item(id):
    view_name = 'product_purchase_item'
    model = ProductPurchaseItem
    item = model.query.get_or_404(id)
    parent_id = item.order.id
    db.session.delete(item)
    flash('Item has been deleted.')
    return redirect(url_for('.create_'+view_name, parent_id=parent_id))



#product_purchase_item
# @product.route('/purchase/<int:parent_id>/item/')
# @login_required
# def list_product_purchase_item(parent_id):
#     view_name = 'product_purchase_item'
#     model = ProductPurchaseItem
#     page = request.args.get('page', 1, type=int)
#     pagination = model.query.filter_by(order_id=parent_id).paginate(
#         page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
#         error_out=False)
#     items = pagination.items
#     return render_template('list.html', 
#         items=items, 
#         pagination=pagination, 
#         view_name=view_name,
#         parent_id=parent_id)


# @product.route('/_add_numbers')
# def add_numbers():
#     status = request.args.get('status')
#     parent_id = request.args.get('parent_id')
#     item = ProductPurchaseOrder.query.get(parent_id)
#     item.status = status
#     db.session.add(item)
#     db.session.commit()
#     return jsonify(result=item.status)

# {% block scripts %}
# {{ super() }}
# <script type=text/javascript>
#   $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
# </script>
# <script type=text/javascript>
#   function order_status(status) {
#       $.getJSON($SCRIPT_ROOT + '/product/_add_numbers', {
#         parent_id: {{ parent.id }},
#         status: status,
#       }, function(data) {
#         $("#statusDiv").load(location.href+" #statusDiv>*","");
#         $("#formDiv").load(location.href+" #formDiv>*","");
#       });
#       return false;
#   }
# </script>
# {% endblock scripts %}


# @login_required
# def edit_product_purchase_order(id):
#     view_name = 'product_purchase_order'
#     model = ProductPurchaseOrder
#     item = model.query.get_or_404(id)
#     form = ProductPurchaseOrderForm()
#     if form.validate_on_submit():
#         item.supplier_id = form.supplier.data
#         db.session.add(item)
#         flash('Item has been updated.')
#         return redirect(url_for('.edit_'+view_name, id=item.id))
#     form.supplier.data = item.supplier_id
#     return render_template('form.html', 
#         form=form, 
#         id=id, 
#         view_name=view_name)

app/finance/templates/report_by_day.html
{% extends "base.html" %}

{% block title %}Report{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="pull-left">
        <div class="btn-group btn-group-sm">
          <a class="btn btn-default" href="{{ url_for('.report_by_day', year=previous_date.year, month=previous_date.month, day=previous_date.day) }}">&lsaquo;</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_day', year=next_date.year, month=next_date.month, day=next_date.day) }}">&rsaquo;</a>
        </div>
        <a class="btn btn-default btn-sm {% if today.year == year and today.month == month and today.day == day %}disabled{% endif %}" href="{{ url_for('.report_by_day') }}">Current</a>
      </div>
    </div>
    <div class="col-sm-4 text-center">
      <h3 class="calendar-header-title">{{ day }} {{ month|month_name }} {{ year }}</h3>
    </div>
    <div class="col-sm-4">
      <div class="pull-right">
        <div class="btn-group btn-group-sm">
          <a class="btn btn-default" href="{{ url_for('.report_by_year', year=year) }}">Year</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_month', year=year, month=month) }}">Month</a>
          <a class="btn btn-default disabled" href="{{ url_for('.report_by_day', year=year, month=month, day=day) }}">Day</a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12">
          {% if items %}
          <table class="table table-striped table-hover table-condensed table-responsive">
            <thead>
              <tr>
                <th>Time</th>
                <th>Transaction</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in items %}
              <tr>
                <td>{{ transaction.date|datetimeformat('%H:%M:%S') }}</td>
                <td><a href="{{ url_for('.report_by_transaction', transaction_id=transaction.transaction_id) }}">{{ transaction }}</a></td>
                <td>{{ transaction.value|float }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot class="table-footer">
              <tr>
                <td>Total</td>
                <td></td>
                <td>{{ total_value|float }}</td>
              </tr>
            </tfoot>
          </table>
          {% else %}
          <p>No record found</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock content %}

app/finance/templates/report_by_month.html
{% extends "base.html" %}

{% block title %}Report{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="pull-left">
        <div class="btn-group btn-group-sm">
          <a class="btn btn-default" href="{{ url_for('.report_by_month', year=previous_date.year, month=previous_date.month) }}">&lsaquo;</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_month', year=next_date.year, month=next_date.month) }}">&rsaquo;</a>
        </div>
        <a class="btn btn-default btn-sm {% if today.year == year and today.month == month %}disabled{% endif %}" href="{{ url_for('.report_by_month') }}">Current</a>
      </div>
    </div>
    <div class="col-sm-4 text-center">
      <h3 class="calendar-header-title">{{ month|month_name }} {{ year }}</h3>
    </div>
    <div class="col-sm-4">
      <div class="pull-right">
        <div class="btn-group btn-group-sm">
          <a class="btn btn-default" href="{{ url_for('.report_by_year', year=year) }}">Year</a>
          <a class="btn btn-default disabled" href="{{ url_for('.report_by_month', year=year, month=month) }}">Month</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_day', year=year, month=month, day=day) }}">Day</a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12">
          {% if items %}
          <table class="table table-striped table-hover table-condensed table-responsive">
            <thead>
              <tr>
                <th>Date</th>
                <th>Transaction</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in items %}
              <tr>
                <td><a href="{{ url_for('.report_by_day', year=year, month=month, day=transaction.date.day) }}">{{ transaction.date|datetimeformat }}</a></td>
                <td><a href="{{ url_for('.report_by_transaction', transaction_id=transaction.transaction_id) }}">{{ transaction }}</a></td>
                <td>{{ transaction.value|float }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot class="table-footer">
              <tr>
                <td>Total</td>
                <td></td>
                <td>{{ total_value|float }}</td>
              </tr>
            </tfoot>
          </table>
          {% else %}
          <p>No record found</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock content %}

app/finance/templates/report_by_transaction.html
{% extends "base.html" %}

{% block title %}Report{% endblock title %}

{% block content %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-sm-12">
          <h3 class="panel-title">Report:</h3>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12">
          {% if items %}
          <table class="table table-striped table-hover table-condensed table-responsive">
            <thead>
              <tr>
                <th>Date</th>
                <th>Description</th>                
                <th>Transaction ID</th>
                <th>Value</th>
                <th class="table-toolbar"></th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in items %}
              <tr>
                <td>{{ transaction.date|datetimeformat }}</td>
                <td>{{ transaction.description }}</td>
                <td><a href="{{ url_for('.edit_financial_transaction', id=transaction.id) }}">{{ transaction.transaction_id }}</a></td>
                <td>{{ transaction.value|float }}</td>
                <td>
                </td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot class="table-footer">
              <tr>
                <td>Total</td>
                <th></th>
                <th></th>
                <td>{{ total_value|float }}</td>
                <td></td>
              </tr>
            </tfoot>
          </table>
          {% else %}
          <p>No record found</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

</div>

{% include "_deleteConfirmModal.html" %}
{% endblock content %}

app/finance/templates/report_by_year.html
{% extends "base.html" %}

{% block title %}Report{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="pull-left">
        <div class="btn-group btn-group-sm">
          <a class="btn btn-default" href="{{ url_for('.report_by_year', year=previous_date.year) }}">&lsaquo;</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_year', year=next_date.year) }}">&rsaquo;</a>
        </div>
        <a class="btn btn-default btn-sm {% if today.year == year %}disabled{% endif %}" href="{{ url_for('.report_by_year') }}">Current</a>
      </div>
    </div>
    <div class="col-sm-4 text-center">
      <h3 class="calendar-header-title">{{ year }}</h3>
    </div>
    <div class="col-sm-4">
      <div class="pull-right">
        <div class="btn-group btn-group-sm">
          <a class="btn btn-default disabled" href="{{ url_for('.report_by_year', year=year) }}">Year</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_month', year=year, month=month) }}">Month</a>
          <a class="btn btn-default" href="{{ url_for('.report_by_day', year=year, month=month, day=day) }}">Day</a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12">
          {% if items %}
          <table class="table table-striped table-hover table-condensed table-responsive">
            <thead>
              <tr>
                <th>Date</th>          
                <th>Transaction</th>
                <th>Model</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in items %}
              <tr>
                <td><a href="{{ url_for('.report_by_month', year=year, month=month) }}">{{ transaction.date|datetimeformat }}</a></td>              
                <td><a href="{{ url_for('.report_by_transaction', transaction_id=transaction.transaction_id) }}">{{ transaction }}</a></td>
                <td><a href="{{ url_for('product.create_product_purchase_item', parent_id=transaction.id) }}">{{ transaction.id }}</a></td>
                <td>{{ transaction.value|float }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot class="table-footer">
              <tr>
                <td>Total</td>
                <td></td>
                <td></td>
                <td>{{ total_value|float }}</td>
              </tr>
            </tfoot>
          </table>
          {% else %}
          <p>No record found</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock content %}