app/finance/views.py
import datetime
from dateutil.relativedelta import relativedelta

from sqlalchemy.sql import func

from flask import Blueprint, render_template, redirect, request, url_for, flash, current_app
from flask_login import current_user, login_required

from .. import db

from ..views import ListView, CreateView, UpdateView, DeleteView

from .models import FinancialTransaction
from .forms import FinancialTransactionForm

finance = Blueprint('finance', __name__, template_folder='templates', url_prefix='/finance')


#finance
finance.add_url_rule('/', view_func=ListView.as_view('list_financial_transaction', FinancialTransaction))
finance.add_url_rule('/add/', view_func=CreateView.as_view('create_financial_transaction', FinancialTransaction, FinancialTransactionForm))
finance.add_url_rule('/<int:id>/', view_func=UpdateView.as_view('edit_financial_transaction', FinancialTransaction, FinancialTransactionForm))
finance.add_url_rule('/<int:id>/delete', view_func=DeleteView.as_view('delete_financial_transaction', FinancialTransaction))

today = datetime.date.today()

@finance.route('/report/daily/', defaults={'year':today.year, 'month':today.month, 'day':today.day})
@finance.route('/report/<int:year>/<int:month>/<int:day>/')
@login_required
def report_by_day(year, month, day):
    view_name = 'report_by_day'
    model = FinancialTransaction
    today = datetime.date.today()
        
    date = datetime.date(year=year, month=month, day=day)
    previous_date = date - relativedelta(days=1)
    next_date = date + relativedelta(days=1)
    
    items = model.query.filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month, func.extract('day', model.date)==day).all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month, func.extract('day', model.date)==day)
    total_value = items_func.first().total_value

    return render_template('report_by_day.html', 
        items=items,
        view_name=view_name,
        year=year,
        month=month,
        day=day,
        today=today,
        previous_date=previous_date,
        next_date=next_date,
        total_value=total_value)


# @finance.route('/report/')
@finance.route('/report/monthly/', defaults={'year':today.year, 'month':today.month})
@finance.route('/report/<int:year>/<int:month>/', methods=['GET', 'POST'])
@login_required
def report_by_month(year, month):
    view_name = 'report_by_month'
    model = FinancialTransaction
    today = datetime.date.today()
    
    year = today.year if not year else year
    month = today.month if not month else month   
    day = today.day if month == today.month else 1
    
    date = datetime.date(year=year, month=month, day=day)
    previous_date = date - relativedelta(months=1)
    next_date = date + relativedelta(months=1)
    
    items = model.query.filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month).all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(func.extract('year', model.date)==year, func.extract('month', model.date)==month)
    total_value = items_func.first().total_value
    
    return render_template('report_by_month.html', 
        items=items,
        view_name=view_name,
        year=year,
        month=month,
        day=day,
        today=today,
        previous_date=previous_date,
        next_date=next_date,
        total_value=total_value)


@finance.route('/report/yearly/', defaults={'year':today.year})
@finance.route('/report/<int:year>/')
@login_required
def report_by_year(year):
    view_name = 'report_by_year'
    model = FinancialTransaction
    today = datetime.date.today()
        
    month = today.month if year == today.year else 1
    day = today.day if month == today.month else 1

    date = datetime.date(year=year, month=month, day=day)
    previous_date = date - relativedelta(years=1)
    next_date = date + relativedelta(years=1)
    
    items = model.query.filter(func.extract('year', model.date)==year).all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(func.extract('year', model.date)==year)
    total_value = items_func.first().total_value
    
    return render_template('report_by_year.html', 
        items=items,
        view_name=view_name,
        year=year,
        month=month,
        day=day,
        today=today,
        previous_date=previous_date,
        next_date=next_date,
        total_value=total_value)

@finance.route('/report/transaction/', defaults={'transaction_id':None})
@finance.route('/report/transaction/<transaction_id>/')
@login_required
def report_by_transaction(transaction_id):
    view_name = 'report_by_transaction'
    model = FinancialTransaction
    
    if transaction_id:
        items = model.query.filter_by(transaction_id=transaction_id).all()
    else:
        items = model.query.all()
    items_func = db.session.query(func.sum(model.value).label('total_value')).filter(model.transaction_id==transaction_id)
    total_value = items_func.first().total_value
 
    return render_template('report_by_transaction.html', 
        items=items,
        view_name=view_name,
        transaction_id=transaction_id,
        total_value=total_value)



# @finance.route('/add/', methods=['GET', 'POST'])
# def create_financial_transaction():
# 	print dir(current_user)
# 	view_name = 'financial_transaction'
# 	form = FinancialTransactionForm()
# 	if form.validate_on_submit():
# 	    item = FinancialTransaction(
# 	        description=form.description.data,
# 	        value=form.value.data,
# 	        employee_id=current_user.id)
# 	    db.session.add(item)
# 	    db.session.commit()
# 	    flash('Item has been recorded.')
# 	    return redirect(url_for('.edit_'+view_name, id=item.id))
# 	return render_template('form.html', form=form, view_name=view_name)

app/product/views.py
import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app, jsonify
from flask_login import login_required, current_user

from ..views import ListView, CreateView, UpdateView, DeleteView
from .. import db
# from . import product

from .models import Status, Product, ProductPurchaseOrder, ProductPurchaseItem, ProductSalesOrder, ProductSalesItem
from .forms import ProductForm, ProductPurchaseOrderForm, ProductPurchaseOrderUpdateForm, ProductPurchaseItemForm, ProductSalesOrderForm, ProductSalesItemForm
from ..organization.models import Supplier
from ..finance.models import FinancialTransaction

product = Blueprint('product', __name__, template_folder='templates', url_prefix='/product')


#product
product.add_url_rule('/product/', view_func=ListView.as_view('list_product', Product))
product.add_url_rule('/product/add/', view_func=CreateView.as_view('create_product', Product, ProductForm))
product.add_url_rule('/product/<int:id>/', view_func=UpdateView.as_view('edit_product', Product, ProductForm))
product.add_url_rule('/product/<int:id>/delete', view_func=DeleteView.as_view('delete_product', Product))
# product.add_url_rule('/purchase/', view_func=ListView.as_view('list_product_purchase_order', ProductPurchaseOrder))


#product_purchase_order
@product.route('/purchase/')
@login_required
def list_product_purchase_order():
    view_name = 'product_purchase_order'
    model = ProductPurchaseOrder
    page = request.args.get('page', 1, type=int)
    pagination = model.query.paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'], error_out=False)
    items = pagination.items
    return render_template('purchase_order/list.html', 
        items=items,
        pagination=pagination, 
        view_name=view_name,
        parent_view_name='product_purchase_item')


@product.route('/purchase/add/', methods=['GET', 'POST'])
@login_required
def create_product_purchase_order():
    view_name = 'product_purchase_order'
    form = ProductPurchaseOrderForm()
    if form.validate_on_submit():
        item = ProductPurchaseOrder(
            employee_id=current_user.id,
            supplier_id=form.supplier.data,
            status=Status.CREATED
        )
        db.session.add(item)
        db.session.commit()
        flash('Item has been recorded.')
        return redirect(url_for('.create_product_purchase_item', parent_id=item.id))
    return render_template('form.html', form=form, view_name=view_name)


@product.route('/purchase/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete_product_purchase_order(id):
    view_name = 'product_purchase_order'
    model = ProductPurchaseOrder
    item = model.query.get_or_404(id)
    db.session.delete(item)
    flash('Item has been deleted.')
    return redirect(url_for('.list_'+view_name))

# @product.route('/purchase/add/', methods=['GET', 'POST'])
@product.route('/purchase/<int:parent_id>/', methods=['GET', 'POST'])
@product.route('/purchase/<int:parent_id>/<status>/', methods=['GET'])
@login_required
def create_product_purchase_item(parent_id=None, status=None):
    view_name = 'product_purchase_item'

    parent = ProductPurchaseOrder.query.get(parent_id)
    parentForm = ProductPurchaseOrderForm()
    print (parent)

    """
    Se <status> for igual a:
    1. CREATED = somente neste status o pedido pode ser alterado.
    2. PLACED = envia email ao fornecedor solicitando a cotacao.
    3. PAID = registra uma transacao financeira.
    4. AVAILABLE = adiciona a quantidade comprada do item ao produto e lanca o valor da compra como despesa.
    """
    if status:
        print (status)
        parent.status = status
        if status == Status.AVAILABLE:
            for product in parent.items:
                product.product.quantity += product.quantity

            parent.financial_transaction = FinancialTransaction(
                description = 'Purchase Order: %s' % parent,
                value = parent.total_value,
                employee_id=current_user.id)
        # if status == Status.PAID:

            
        # db.session.add(parent)
        return redirect(url_for('.create_'+view_name, parent_id=parent_id))

    form = ProductPurchaseItemForm()
    if form.validate_on_submit():
        item = ProductPurchaseItem(
            order_id=parent_id,
            product_id=form.product.data,
            quantity=form.quantity.data,
            value=form.value.data,
            status=Status.CREATED)
        db.session.add(item)
        db.session.commit()
        flash('Item has been recorded.')
        return redirect(url_for('.edit_'+view_name, 
            parent_id=item.order.id, 
            id=item.id))

    page = request.args.get('page', 1, type=int)
    pagination = ProductPurchaseItem.query.filter_by(order_id=parent_id).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    items = pagination.items
    return render_template('purchase_item/form_list.html',
        view_name=view_name,
        form=form,
        parentForm=parentForm,
        items=items,
        pagination=pagination, 
        parent=parent)


@product.route('/purchase/<int:parent_id>/item/<int:id>/', methods=['GET', 'POST'])
@login_required
def edit_product_purchase_item(parent_id, id):
    view_name = 'product_purchase_item'
    form = ProductPurchaseItemForm()
    item = ProductPurchaseItem.query.get_or_404(id)
    if form.validate_on_submit():
        item.product_id = form.product.data
        item.quantity = form.quantity.data
        item.value = form.value.data
        db.session.add(item)
        flash('Item has been updated.')
        return redirect(url_for('.edit_'+view_name, 
            id=item.id,
            parent_id=item.order.id))
    form.product.data = item.product_id
    form.quantity.data = item.quantity
    form.value.data = item.value

    page = request.args.get('page', 1, type=int)
    pagination = ProductPurchaseItem.query.filter_by(order_id=parent_id).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    items = pagination.items
    return render_template('purchase_item/form_list.html', 
        view_name=view_name,
        form=form,
        items=items,
        pagination=pagination, 
        id=id,
        parent=item.order)


@product.route('/purchase/item/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete_product_purchase_item(id):
    view_name = 'product_purchase_item'
    model = ProductPurchaseItem
    item = model.query.get_or_404(id)
    parent_id = item.order.id
    db.session.delete(item)
    flash('Item has been deleted.')
    return redirect(url_for('.create_'+view_name, parent_id=parent_id))



#product_purchase_item
# @product.route('/purchase/<int:parent_id>/item/')
# @login_required
# def list_product_purchase_item(parent_id):
#     view_name = 'product_purchase_item'
#     model = ProductPurchaseItem
#     page = request.args.get('page', 1, type=int)
#     pagination = model.query.filter_by(order_id=parent_id).paginate(
#         page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
#         error_out=False)
#     items = pagination.items
#     return render_template('list.html', 
#         items=items, 
#         pagination=pagination, 
#         view_name=view_name,
#         parent_id=parent_id)


# @product.route('/_add_numbers')
# def add_numbers():
#     status = request.args.get('status')
#     parent_id = request.args.get('parent_id')
#     item = ProductPurchaseOrder.query.get(parent_id)
#     item.status = status
#     db.session.add(item)
#     db.session.commit()
#     return jsonify(result=item.status)

# {% block scripts %}
# {{ super() }}
# <script type=text/javascript>
#   $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
# </script>
# <script type=text/javascript>
#   function order_status(status) {
#       $.getJSON($SCRIPT_ROOT + '/product/_add_numbers', {
#         parent_id: {{ parent.id }},
#         status: status,
#       }, function(data) {
#         $("#statusDiv").load(location.href+" #statusDiv>*","");
#         $("#formDiv").load(location.href+" #formDiv>*","");
#       });
#       return false;
#   }
# </script>
# {% endblock scripts %}


# @login_required
# def edit_product_purchase_order(id):
#     view_name = 'product_purchase_order'
#     model = ProductPurchaseOrder
#     item = model.query.get_or_404(id)
#     form = ProductPurchaseOrderForm()
#     if form.validate_on_submit():
#         item.supplier_id = form.supplier.data
#         db.session.add(item)
#         flash('Item has been updated.')
#         return redirect(url_for('.edit_'+view_name, id=item.id))
#     form.supplier.data = item.supplier_id
#     return render_template('form.html', 
#         form=form, 
#         id=id, 
#         view_name=view_name)

app/templates/_deleteConfirmModal.html
<div id="deleteConfirmModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 id="deleteConfirmModalLabel" class="modal-title">Confirm delete</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Cancel</a>
        <a id="deleteConfirmButton" class="btn btn-danger">Delete</a>
      </div>
    </div><!-- /.modal-content 
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
  function deleteConfirmModal(url, msg) {
    $('#deleteConfirmModal').modal('show'); 
    $('#deleteConfirmButton').attr('href', url);
    if (msg) {
      $("p").html(msg);
    }
  }
</script>

app/templates/_navbar.html
<header class="site-header">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Virtuasi</a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Organization<i class="fa fa-caret-down fa-fw"></i></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('organization.list_organization') }}">Organization</a></li>
                    <li><a href="{{ url_for('organization.list_employee') }}">Employee</a></li>
                    <li><a href="{{ url_for('organization.list_customer') }}">Customer</a></li>
                    <li><a href="{{ url_for('organization.list_supplier') }}">Supplier</a></li>
                  </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Product<i class="fa fa-caret-down fa-fw"></i></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('product.list_product') }}">Product</a></li>
                    <li><a href="{{ url_for('product.list_product_purchase_order') }}">Product Purchase Order</a></li>
                  </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Location<i class="fa fa-caret-down fa-fw"></i></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('location.list_country') }}">Country</a></li>
                    <li><a href="{{ url_for('location.list_state') }}">State</a></li>
                    <li><a href="{{ url_for('location.list_city') }}">City</a></li>
                    <li><a href="{{ url_for('location.list_district') }}">District</a></li>
                    <li><a href="{{ url_for('location.list_address') }}">Address</a></li>
                  </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Building<i class="fa fa-caret-down fa-fw"></i></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('building.list_condominium') }}">Condominium</a></li>
                    <li><a href="{{ url_for('building.list_building') }}">Building</a></li>
                    <li><a href="{{ url_for('building.list_room') }}">Room</a></li>
                    <li><a href="{{ url_for('building.list_area') }}">Area</a></li>
                  </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Report<i class="fa fa-caret-down fa-fw"></i></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('finance.report_by_day') }}">Daily</a></li>
                    <li><a href="{{ url_for('finance.report_by_month') }}">Monthly</a></li>
                    <li><a href="{{ url_for('finance.report_by_year') }}">Yearly</a></li>
                    <li><a href="{{ url_for('finance.report_by_transaction') }}">Transaction</a></li>
                  </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.gravatar(size=18) }}">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a>Organizations</a></li>
                        <li class="divider"></li>

                        <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.register') }}">Sign up</a></li>
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
  </nav>
</header>

app/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
            <div class="post-body">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
            <div class="post-footer">
                {% if current_user == post.author %}
                <a href="{{ url_for('.edit', id=post.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('.edit', id=post.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                {% endif %}
                <a href="{{ url_for('.post', id=post.id) }}">
                    <span class="label label-default">Permalink</span>
                </a>
                <a href="{{ url_for('.post', id=post.id) }}#comments">
                    <span class="label label-primary">{{ post.comments.count() }} Comments</span>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/admin.html
{% extends 'admin/master.html' %}

{% block body %}
  <p>Admin</p>
{% endblock %}

app/templates/base.html
{%- extends "bootstrap/base.html" %}
{% import "bootstrap/fixes.html" as fixes %}

{% block title %}Page Title{% endblock %}

{% block head %}
  {{super()}}
  {{fixes.ie8()}}
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{%- endblock %}

{% block metas -%}
  {{super()}}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Virtua Gestao Total">
  <meta name="author" content="Virtuasi">
{% endblock metas %}
    
{% block styles -%}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}">
{% endblock %}

{% block body %}

  {% block navbar %}
    {% include '_navbar.html' %}
  {%- endblock navbar %}

  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for message in get_flashed_messages() %}
          <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ message }}
          </div>
          {% endfor %}
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}"> {{ category }} ==
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    {% endwith %}
    
    {% block content %}{% endblock content %}

    {% if error %}
      <p class="error"><strong>Error:</strong> {{ error }}</p>
    {% endif %}
  </div>

  {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {{ moment.include_moment() }}
  {% endblock scripts %}

{% endblock body %}

app/templates/base2.html
<!DOCTYPE html>
<html lang="{{request.locale_name}}" {% block html_attribs %}{% endblock html_attribs %}>
  <head>
  {% block head %}
    <title>{% block title %}Site Title{% endblock title %}</title>
    {% block metas %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Virtua Gestao Total">
    <meta name="author" content="Virtuasi">
    {% endblock metas %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/dist/css/bootstrap.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}">
    {% endblock styles %}
  {% endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
  {% block body %}

    {% block header %}
        {% include '_navbar.html' %}
    {% endblock header %}
    
    {% block body_content %}
    <div class="container">    
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
          <div class="col-md-12">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}"> {{ category }} ==
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
      {% endwith %}
      
      {% block content %}{% endblock content %}

      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
      {% endif %}
    </div>
    {% endblock body_content %}

    {% block footer %}{% include '_footer.html' %}{% endblock footer %}

    {% block scripts %}
    <script src="{{ url_for('static', filename='jquery/dist/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/dist/js/bootstrap.js') }}"></script>
    {{ moment.include_moment() }}
    {% endblock scripts %}
    
  {% endblock body %}
  </body>
</html>

app/templates/error_page.html
{% extends "base.html" %}

{% block title %}Flasky - {{ code }}: {{ name }}{% endblock %}

{% block content %}
<div class="page-header">
    <h1>{{ code }}: {{ name }}</h1>
    <p>{{ description }}</p>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Flasky{% endblock %}

{% block content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
<div>
    {% if current_user.can(Permission.WRITE_ARTICLES) %}
    {{ macros.quick_form(form) }}
    {% endif %}
</div>
<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li{% if not show_followed %} class="active"{% endif %}><a href="{{ url_for('.show_all') }}">All</a></li>
        {% if current_user.is_authenticated %}
        <li{% if show_followed %} class="active"{% endif %}><a href="{{ url_for('.show_followed') }}">Followers</a></li>
        {% endif %}
    </ul>
    {% include '_posts.html' %}
</div>
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/moderate.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Flasky - Comment Moderation{% endblock %}

{% block content %}
<div class="page-header">
    <h1>Comment Moderation</h1>
</div>
{% set moderate = True %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.moderate') }}
</div>
{% endif %}
{% endblock %}